### ISSUE TITLE
Roadmap Cost Calculation

### ISSUE THREAD

**Issue by Plutoberth** [nzo-heschel/MillionSuns#4]
This task has a few parts:

- [x] Identify the required parameters related to costs (interest, opex, capex, for example), and write a small doc about each of them. This also includes a sensible default value and its source.
- [x] Figure out a model for pricing, that factors in at least what the original model did. You can look at `calculateScenariosAndCosts` and `calculateCosts` for inspiration.
- [x] Given a roadmap (which is a collection of scenarios for every year), figure out the costs for each year (like the costs part of the `scenarios-output` table). Some non-trivial calculations are needed, for example calculating the capex of new solar installations per year. 

ℹ️ This is already partially implemented [here](https://github.com/Plutoberth/MillionSuns/blob/master/hourly_simulation/simulation.py#L30).

**Comment by Plutoberth** [comment]
Closed by #30
